### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by partrita** [r4lv/jpy-flette#1]
```
Traceback (most recent call last):
  File "/home/deepthought/.pyenv/versions/3.7.0/bin/jpy-flette", line 11, in <module>
    sys.exit(cli())
  File "/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/jpy_flette/jpy_flette.py", line 54, in cli
    with open(resource("fletteconf-default.yaml")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/deepthought/.pyenv/versions/3.7.0/lib/python3.7/site-packages/jpy_flette/fletteconf-default.yaml'

```
seems like i need fletteconf-default.yaml files.

**Comment by partrita** [comment]
I use `pip install jpy-flette` command
